version: 0.2 
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish AWSLambda1.csproj -c Release -o bin/Release/netcoreapp1.0/publish
      - cd bin/Release/netcoreapp1.0/publish
      - zip ../test.zip *
      - cd ..
      - aws lambda update-function-code --function-name myBirthYearLambdaFunction --zip-file fileb://test.zip