version: 0.2 
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish AWSLambda1/AWSLambda1.csproj -c Release -o bin/Release/netcoreapp1.0/publish/AWSLambda1
      - cd AWSLambda1/AWSLambda1/bin/Release/netcoreapp1.0/publish/AWSLambda1
      - zip ../../../../../../Artifacts/AWSLambda.zip*